apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    metadata:
      name: db-migration
    spec:
      containers:
        - name: db-migration
          image: nyuappsec/assign3:v0
          command: ["python3", "manage.py", "migrate"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              # value: thisisatestthing.
              valueFrom:
                      secretKeyRef:
                              name: part1-secrets
                              key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DB
              value: GiftcardSiteDB

            - name: MYSQL_HOST
              value: mysql-service

            - name: ALLOWED_HOSTS
              value: "*,"

            - name: SECRET_KEY
              valueFrom:
                      secretKeyRef:
                              name: part1-django-secrets
                              key: SECRET_KEY

      restartPolicy: Never
  backoffLimit: 4
            
